"""
    RTLOC

    COMMANDS.py

    (c) 2020-2022 RTLOC/Callitrix NV. All rights reserved.

    Jasper Wouters <jasper@rtloc.com>
    Frederic Mes <fred@rtloc.com>

"""

"""
Command definitions
"""
_UART_HEADER_PREAMBLE = 0x23
TARGET_ADHOC = b'\x07'


# Commands
_SD_UART_CMD_START_STREAMING = 0x05
_SD_UART_CMD_STOP_STREAMING = 0x06
_SD_UART_CMD_GET_DISTANCES = 0x07
_SD_UART_CMD_GET_DISTANCE_OF = 0x08
_SD_UART_CMD_GET_BATTERY_LVL = 0x09
_SD_UART_CMD_GET_INT_ADDR = 0x0a
_SD_UART_CMD_GET_INT_ADDR = 0x0a
_SD_UART_CMD_GET_PROPS = 36
_SD_UART_CMD_PROPS = 24
_SD_UART_CMD_CLEAR_CONFIG = 50
_SD_UART_CMD_DISTANCES = 2
_SD_UART_CMD_UPLOAD_ANCHOR_IN = 10
_SD_UART_CMD_UPLOAD_ANCHOR_OUT = 11
_SD_UART_CMD_UPLOAD_OK = 23