#################################################
# INTERFACE CONFIGS
#################################################

#Windows style
serial_port: COM5

# Unix style
# serial_port: /dev/ttyACM0
# serial_port: /dev/tty.usbserial-A900fu2k
# serial_port: /dev/tty.usbmodem21401
